processor_images = {
        "ocrd": "ocrd/all:maximum",
        "ocrd-olena-binarize": "ocrd/all:maximum",
        "ocrd-sbb-binarize": "ocrd/all:maximum",
        "ocrd-sbb-textline-detector": "ocrd/all:maximum",
        "ocrd-calamari-recognize": "ocrd/all:maximum",
        "ocrd-calamari-recognize03": "ocrd/all:maximum",
        "ocrd-tesserocr-segment-region": "ocrd/all:maximum",
        "ocrd-tesserocr-segment-line": "ocrd/all:maximum",
        "ocrd-tesserocr-recognize": "ocrd/all:maximum",
        "ocrd-dinglehopper": "ocrd/all:maximum",
        "ocrd-cis-ocropy-clip": "ocrd/all:maximum",
        "ocrd-cis-ocropy-resegment": "ocrd/all:maximum",
        "ocrd-cis-ocropy-segment": "ocrd/all:maximum",
        "ocrd-cis-ocropy-deskew": "ocrd/all:maximum",
        "ocrd-cis-ocropy-denoise": "ocrd/all:maximum",
        "ocrd-cis-ocropy-binarize": "ocrd/all:maximum",
        "ocrd-cis-ocropy-dewarp": "ocrd/all:maximum",
        "ocrd-cis-ocropy-recognize": "ocrd/all:maximum",
        "ocrd-fileformat-transform": "ocrd/all:maximum",
        "ocrd-segment-extract-pages": "ocrd/all:maximum",
        "ocrd-segment-extract-regions": "ocrd/all:maximum",
        "ocrd-segment-extract-lines": "ocrd/all:maximum",
        "ocrd-segment-from-masks": "ocrd/all:maximum",
        "ocrd-segment-from-coco": "ocrd/all:maximum",
        "ocrd-segment-repair": "ocrd/all:maximum",
        "ocrd-segment-evaluate": "ocrd/all:maximum",
        "ocrd-preprocess-image": "ocrd/all:maximum",
        "ocrd-skimage-normalize": "ocrd/all:maximum",
        "ocrd-skimage-denoise-raw": "ocrd/all:maximum",
        "ocrd-skimage-binarize": "ocrd/all:maximum",
        "ocrd-skimage-denoise": "ocrd/all:maximum",
        "ocrd-eynollah-segment": "ocrd/all:maximum",
        "ocrd-anybaseocr-binarize": "ocrd/all:maximum",
        "ocrd-anybaseocr-crop": "ocrd/all:maximum",
        "ocrd-anybaseocr-deskew": "ocrd/all:maximum",

        # non OCR-D CLI
        "ocr-transform": "ocrd/all:maximum",
        "dinglehopper": "ocrd/all:maximum",
        "dinglehopper-extract": "ocrd/all:maximum",

        # specialized images
        "ocrd-trocr-recognize": "ocrd_trocr",
}
