kind: pipeline
name: default

steps:
- name: prepare data
  image: alpine
  commands:
  - apk update && apk add bash curl
  - FORCE_DOWNLOAD=y ./build-tmp-XXX
- name: build core
  image: plugins/docker
  settings:
    repo: my_ocrd_workflow-core
    dockerfile: Dockerfile-core
