kind: pipeline
name: default

steps:
- name: prepare data
  image: alpine
  commands:
  - apk update && apk add bash
  - ./build-tmp-XXX
- name: build core
  image: plugins/docker
  dockerfile: Dockerfile-core

