kind: pipeline
name: default

steps:
- name: prepare data
  image: alpine
  commands:
  - apk update && apk add bash curl
  - FORCE_DOWNLOAD=y ./build-tmp-XXX
- name: build core
  image: plugins/docker
  settings:
    repo: mikegerber/my_ocrd_workflow-core
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: Dockerfile-core
