language: generic

services:
  - docker

git:
  submodules: false  # Avoid trying to checkout private data/ submodule

install:
  - FORCE_GET_FROM_WEB=y ./build

script:
  - curl -O https://qurator-data.de/examples/actevedef_718448162.first-page.zip
  - unzip actevedef_718448162.first-page.zip
  - cd actevedef_718448162.first-page

  - $TRAVIS_BUILD_DIR/run
