language: generic

services:
  - docker

git:
  submodules: false  # Avoid trying to checkout private data/ submodule

install:
  - FORCE_DOWNLOAD=y ./build

script:
  - curl -O https://qurator-data.de/examples/actevedef_718448162.first-page.zip
  - unzip actevedef_718448162.first-page.zip
  - cd actevedef_718448162.first-page

  - $TRAVIS_BUILD_DIR/run

  - grep -q 'auswaͤrtige Rechtsgelaͤhrte haͤtten muͤſſen bef.aget werden' OCR-D-OCR-CALAMARI/OCR-D-OCR-CALAMARI_00000024.xml
  - grep -q 'auswaͤrtige Rechtsgelaͤhrte haͤtten muͤſſen bef.aget werden' OCR-D-OCR-TESS/OCR-D-OCR-TESS_00000024.xml
