FROM ocrd/all:maximum

ARG PIP_INSTALL="pip3 install --no-cache-dir"
ARG OCRD_TROCR_COMMIT="30696cb"


# Build pip installable stuff
RUN ${PIP_INSTALL} \
    https://github.com/qurator-spk/ocrd_trocr/archive/$OCRD_TROCR_COMMIT.tar.gz


# Check pip dependencies
RUN pip check


# Default command
CMD ["ocrd-trocr-recognize"]
