name: build

on:

  workflow_dispatch:

  push:
    branches:
      - 'master'
      - 'test/github-actions'

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.step1.outputs.core }}
      rest: ${{ steps.step1.outputs.rest }}
    steps:
      -
        id: step1
        run: |
          echo "core=$(./.github/list-subimages --core --csv)" >>$GITHUB_OUTPUT
          echo "rest=$(./.github/list-subimages --rest --csv)" >>$GITHUB_OUTPUT

  build-core:
    strategy:
      matrix:
        subimage: ["core"]
    uses: ./.github/workflows/build-subimage.yml
    with:
      subimage: ${{ matrix.subimage }}
      tags: |
        type=sha,format=long
    secrets: inherit

  build-rest:
    needs: build-core
    strategy:
      matrix:
        subimage: ["dinglehopper"]
    uses: ./.github/workflows/build-subimage.yml
    with:
      subimage: ${{ matrix.subimage }}
      tags: |
        type=sha,format=long
    secrets: inherit


  test:
    needs: build-rest
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_TAG: sha-${{ github.sha }}  # needed to run the correct version through the wrapper
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install wrapper
        run: |
          sudo apt-get install -y python3-pip
          cd wrapper && pip install .
      -
        name: Test
        run: |
          ocrd --version
          ocrd-dinglehopper --version


  # At this point, we have successfully built, uploaded and tested the images. We now just need to add
  # tags. We do this by building again, but using the formerly built images to
  # cache from.

  push-with-tags:
    needs: test
    strategy:
      matrix:
        subimage: ["core", "dinglehopper"]
    uses: ./.github/workflows/build-subimage.yml
    with:
      subimage: ${{ matrix.subimage }}
      tags: |
        type=sha,format=long
        type=ref,event=tag
    secrets: inherit
