name: build

on:
  workflow_dispatch:

  push:
    branches:
      - 'master'
      - 'test/github-actions'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        # We are checking out explicitly, so build-push-action isn't trying
        # to checkout the (unreachable) submodule. (Using "context" there.)

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # TODO data
      # TODO matrix for all Dockerfiles

      -
        name: Build core
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-core
          build-args:
            DRONE_COMMIT=${{ github.sha }}
          push: true
          tags: ${{ github.sha }}
      -
        name: Build dinglehopper
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-dinglehopper
          build-args:
            DRONE_COMMIT=${{ github.sha }}
          push: true
          tags: ${{ github.sha }}
