name: Test

on: push

jobs:
  build:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: |-
        FORCE_DOWNLOAD=y ./build 
